/**
 * No.389
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        int sumS=0;
        int sumT=0;
        for(int i=0;i<s.length();i++){
            sumS+=(int)s.charAt(i);
        }
        for(int i=0;i<t.length();i++){
            sumT+=(int)t.charAt(i);
        }
        return (char)(sumT-sumS);
    }

    public static void main(String[] args){
        String s="abcd";
        String t="abcde";
        System.out.println(findTheDifference(s,t));
    }
}
